travis:
  secure:
    BINSTAR_TOKEN: I4wvAdZYQFjSAf5GGz2/nROChZiT6pGm55kxqS8HPPU6IxFmHc/JJ7Pey7itbbh4inEnazptDpU0BZY+q8p4z1jFmPfvqT+M+npLnXQiHJ7l+cqmQeflX76YSDjXc+ODfFsf4GlC5qog9Nx3taI7JGX6tnpXA9KX6u4R0yMSDAh6mz4dZwxPC98JWuQem6soIjdbrKWRjMXR9vdECBdcCokG5XMnbU14z+4gqcWZjHKTijbydU82isylGWTVXXRe7BDiG7k87QidsiVS/LZCuwWFCsnqm5rXsKCIPDzM2syOVxP4NRMeEPzUoCDFVGYt25ryoehCVsLd50l7N7Pjh3ryvLQIOq8XT2LQU8mjzGWkG/EVvIlnHflCGxJt8Rg84K7+WjZC+t1k/ii61yIuvnYnpfDwnGKe47m1X4Gk2dqXXSs+vacLKAdnT1d7VvV3tAITOsRw4h2TOnkocHfpnfai7MkVbQFAJnAo4IAndiMyAsSLfnuENyUUdI4L5pzXsIaUTBgUGuaLIjRouUOJIrhuPg3un3xFK+VJI8mnIHrjwCe2GVDd5z5rrljpZZK0USMTXDBu8sPfAHJL+n0N+ABP2pV1FsywbfWxO4WjiC4n9rhMer0wnAIHpzcP4Ge7MgS1t5fw0b4PKvBRxK+98SMTnQjjCEq7sgq1tL+Nfls=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
